site_name: Chris King - Technical Writer
theme:
  name: material
  logo: logo.png
  features:
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
   # - toc:
   #   title: On this page
   # - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: orange

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Chris_TKing
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chris-king-b2475b8/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree

nav:
    - 'index.md'
    - 'work-history.md'
    - 'writing-samples.md'
    - 'skills-activities.md'
    - 'recommendations.md'

copyright: |
  &copy; 2023 <a href="https://github.com/chris-king1"  target="_blank" rel="noopener">Chris King</a>
